import { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    jobs: "Jobs", 
    internships: "Internships",
    buyProducts: "Buy Products",
    sellItems: "Sell Items",
    contact: "Contact",
    login: "Login",
    signup: "Sign Up",
    
    // Hero Section - New translations
    connectingSkills: "Connecting Skills and Commerce",
    underOneRoof: "Under One Roof",
    heroDescriptionNew: "Whether you're seeking opportunities or offering them, JBS is your gateway to a thriving community of students, professionals, and business owners.",
    exploreJobsInternships: "Explore Jobs & Internships",
    startSellingHiring: "Start Selling or Hiring",
    
    // Stats - New translations
    activeUsers: "Active Users",
    jobsPosted: "Jobs Posted", 
    itemsSold: "Items Sold",
    internshipsOffered: "Internships Offered",
    
    // Categories - New translations
    exploreByCategory: "Explore by Category",
    findOpportunities: "Find part-time and full-time opportunities",
    gainExperience: "Gain experience with top companies",
    shopFromLocal: "Shop from local sellers",
    listProducts: "List your products easily",
    
    // Sections - New translations
    latestJobs: "Latest Jobs",
    latestInternships: "Latest Internships",
    trendingProducts: "Trending Products",
    
    // Product specific
    outOfStock: "Out of Stock",
    soldBy: "Sold by:",
    
    // About section
    aboutPlatformTitle: "About JBS Platform",
    aboutPlatformDesc: "JBS (Jobs, Buying & Selling) is a revolutionary platform that bridges the gap between students seeking opportunities and businesses looking for talent. We create a thriving ecosystem where education meets enterprise, skills meet success, and commerce meets community.",
    forStudents: "For Students",
    forStudentsDesc: "Find part-time jobs, internships, and shop for essentials while building your career.",
    forBusinesses: "For Businesses", 
    forBusinessesDesc: "Hire talented students, sell products, and grow your business with our platform.",
    forGrowth: "For Growth",
    forGrowthDesc: "A platform designed to foster growth, learning, and mutual success for all users.",
    
    // Testimonials
    whatUsersSay: "What Our Users Say",
    
    // Newsletter  
    stayUpdated: "Stay Updated",
    newsletterDescNew: "Subscribe to get the latest job postings, products, and platform updates.",
    enterEmail: "Enter your email",
    
    // Footer
    footerDesc: "Connecting skills and commerce under one roof.",
    contactInfo: "Contact Info",
    
    // Chatbot
    jbsAssistant: "JBS Assistant", 
    askAnything: "Ask me anything about JBS...",
    send: "Send",
    chatbotWelcome: "Hello! I'm your JBS assistant. How can I help you today?",
    chatbotResponse: "Thank you for your question! Our team will get back to you soon. For immediate help, you can also call our support at +91-9876543210.",
    
    // Dashboard navigation and common
    myProfile: "My Profile",
    logout: "Logout",
    welcome: "Welcome",
    notifications: "Notifications",
    search: "Search",
    filter: "Filter",
    apply: "Apply",
    edit: "Edit",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    update: "Update",
    submit: "Submit",
    close: "Close",
    next: "Next",
    previous: "Previous",
    loading: "Loading...",
    noResults: "No results found",
    
    // Form labels
    name: "Name",
    title: "Title",
    location: "Location",
    duration: "Duration",
    type: "Type",
    category: "Category",
    price: "Price",
    amount: "Amount",
    date: "Date",
    time: "Time",
    status: "Status",
    rating: "Rating",
    reviews: "Reviews",
    
    // Job/Internship forms
    jobTitle: "Job Title",
    companyName: "Company Name",
    jobDescription: "Job Description",
    jobRequirements: "Job Requirements",
    salary: "Salary",
    payPerHour: "Pay per hour",
    workingHours: "Working Hours",
    internshipTitle: "Internship Title",
    stipend: "Stipend",
    skillsRequired: "Skills Required",
    
    // Profile fields
    fullName: "Full Name",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    city: "City",
    education: "Education",
    experience: "Experience",
    bio: "Bio",
    phoneNumber: "Phone Number",
    address: "Address",
    pincode: "Pincode",
    
    // Business fields
    businessName: "Business Name",
    businessType: "Business Type",
    businessAddress: "Business Address",
    businessHours: "Business Hours",
    businessDescription: "Business Description",
    gstNumber: "GST Number",
    panNumber: "PAN Number",
    website: "Website",
    
    // Order and tracking
    orderHistory: "Order History",
    orderStatus: "Order Status",
    orderDetails: "Order Details",
    trackOrder: "Track Order",
    orderDate: "Order Date",
    deliveryDate: "Delivery Date",
    totalAmount: "Total Amount",
    
    // Status options
    active: "Active",
    inactive: "Inactive",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    completed: "Completed",
    cancelled: "Cancelled",
    shipped: "Shipped",
    delivered: "Delivered",
    
    // Categories
    electronics: "Electronics",
    books: "Books",
    clothing: "Clothing",
    accessories: "Accessories",
    furniture: "Furniture",
    stationery: "Stationery",
    sports: "Sports",
    health: "Health",
    beauty: "Beauty",
    food: "Food",
    
    // Common messages
    success: "Success",
    error: "Error",
    warning: "Warning",
    info: "Information",
    confirmDelete: "Are you sure you want to delete this item?",
    saveChanges: "Save Changes",
    changessaved: "Changes saved successfully",
    actionCompleted: "Action completed successfully",
    tryAgain: "Please try again",
    
    // Sections
    aboutTitle: "About JBS Platform",
    aboutDescription: "JBS (Jobs-Business-Students) is a revolutionary platform designed to bridge the gap between students seeking opportunities and businesses needing talent. We provide a comprehensive ecosystem where students can find part-time jobs, internships, and purchase essential products at student-friendly prices.",
    whyChooseUs: "Why Choose Us",
    trustedPlatform: "Trusted Platform",
    trustedDesc: "Verified businesses and secure transactions",
    flexibleOpportunities: "Flexible Opportunities", 
    flexibleDesc: "Part-time jobs that fit your schedule",
    studentFocused: "Student-Focused",
    studentDesc: "Designed specifically for student needs",
    localConnect: "Local Connect",
    localDesc: "Connect with businesses in your area",
    
    // Featured sections
    featuredJobs: "Featured Jobs",
    viewAllJobs: "View All Jobs",
    featuredInternships: "Featured Internships", 
    viewAllInternships: "View All Internships",
    viewAllProducts: "View All Products",
    
    // Form labels and buttons
    fullTime: "Full-time",
    partTime: "Part-time",
    paid: "Paid",
    unpaid: "Unpaid",
    inStock: "In Stock",
    all: "All",
    
    // Buttons and actions
    applyNow: "Apply Now",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    learnMore: "Learn More",
    viewDetails: "View Details",
    
    // Product form
    addNewProduct: "Add New Product",
    basicInformation: "Basic Information",
    productName: "Product Name",
    enterProductName: "Enter product name",
    brand: "Brand",
    enterBrand: "Enter brand name",
    originalPrice: "Original Price",
    quantity: "Quantity",
    selectCategory: "Select category",
    condition: "Condition",
    new: "New",
    likeNew: "Like New",
    good: "Good",
    fair: "Fair",
    used: "Used",
    productDetails: "Product Details",
    enterProductDescription: "Enter detailed product description",
    keyFeatures: "Key Features",
    enterKeyFeatures: "Enter key features (one per line)",
    productImages: "Product Images",
    clickToUploadImages: "Click to upload images or drag and drop",
    supportedFormats: "PNG, JPG, GIF up to 10MB",
    availability: "Availability",
    productAdded: "Product Added",
    productAddedSuccessfully: "Your product has been added successfully!",
    addProduct: "Add Product",
    
    // Dashboard
    dashboard: "Dashboard",
    profile: "Profile",
    settings: "Settings",
    notificationsList: "Notifications",
    myOrders: "My Orders",
    analytics: "Analytics",
    aiAssistant: "AI Assistant",
    products: "Products",
    postNewJob: "Post New Job", 
    postNewInternship: "Post New Internship",
    track: "Track",
    
    // Contact and tracking
    customerSupport: "Customer Support",
    technicalSupport: "Technical Support",
    businessInquiries: "Business Inquiries",
    sendFeedback: "Send Feedback",
    trackOrders: "Track Orders",
    trackApplications: "Track Applications",
    trackPerformance: "Track Performance",
    trackInventory: "Track Inventory",
    
    // Footer
    newsletter: "Newsletter",
    subscribeNewsletter: "Subscribe to our newsletter for latest updates",
    subscribe: "Subscribe",
    quickLinks: "Quick Links",
    ourServices: "Our Services",
    followUs: "Follow Us",
    allRightsReserved: "All rights reserved",
    
    // Common actions
    reset: "Reset",
    confirm: "Confirm",
    back: "Back",
    continue: "Continue",
    finish: "Finish",
    retry: "Retry",
    studentRegistration: "Student Registration",
    studentRegistrationDesc: "Join JBS as a student and discover amazing opportunities",
    
    // Toast messages
    addedToCart: "Added to Cart",
    removedFromCart: "Removed from Cart",
    subscribedSuccessfully: "Subscribed Successfully!",
    thankYouForQuestion: "Thank you for your question! Our team will get back to you soon. For immediate help, you can also call our support at +91-9876543210.",
    itemAddedToCart: "has been added to your cart.",
    itemRemovedFromCart: "Item has been removed from your cart.",
    receiveLatestUpdates: "You'll receive the latest updates in your email.",
    

    
    // Common translations
    welcomeBack: "Welcome back",
    loginSuccessful: "Login Successful",
    loginFailed: "Login Failed",
    invalidEmailPassword: "Invalid email or password",
    loggedOut: "Logged Out",
    loggedOutSuccessfully: "You have been successfully logged out",
    backToHome: "Back to Home",
    loggingIn: "Logging in...",
    enterPassword: "Enter password",
    
    // Dashboard stats
    totalProducts: "Total Products",
    totalSold: "Total Sold",
    paidProducts: "Paid Products",
    unpaidProducts: "Unpaid Products",
    totalJobInternshipJoins: "Total Job/Internship Joins",
    paidJoins: "Paid Joins",
    unpaidJoins: "Unpaid Joins",
    
    // Dashboard tables
    jobInternshipDetails: "Job/Internship Details",
    jobInternship: "Job/Internship",
    totalJoined: "Total Joined",
    
    // Products
    manageProducts: "Manage Products",
    qty: "Qty",
    sold: "Sold",
    payment: "Payment",
    seller: "Seller",
    
    // Jobs
    manageJobs: "Manage Jobs",
    addJob: "Add Job",
    
    // Internships
    manageInternships: "Manage Internships",
    addInternship: "Add Internship",
    
    // Payments
    paymentDetails: "Payment Details",
    totalProductPayments: "Total Product Payments",
    totalJobPayments: "Total Job Payments",
    totalInternshipPayments: "Total Internship Payments",
    
    // Business Owners
    businessOwners: "Business Owners",
    viewProfile: "View Profile",
    block: "Block",
    personalInformation: "Personal Information",
    enterFullName: "Enter your full name",
    pickDate: "Pick a date",
    selectGender: "Select gender",
    male: "Male",
    female: "Female",
    other: "Other",
    preferNotToSay: "Prefer not to say",
    enterPhoneNumber: "Enter your phone number",
    enterCity: "Enter your city",
    enterAddress: "Enter your complete address",
    educationInformation: "Education Information",
    educationLevel: "Education Level",
    selectEducationLevel: "Select education level",
    "12thPass": "12th Pass",
    undergraduate: "Undergraduate (Pursuing)",
    graduate: "Graduate",
    postGraduate: "Post Graduate",
    diploma: "Diploma",
    certificateCourse: "Certificate Course",
    bioAboutYourself: "Bio / About Yourself",
    bioPlaceholder: "Tell us about yourself, your goals, and what you're looking for...",
    iHaveWorkExperience: "I have work experience",
    yearsOfExperience: "Years of Experience",
    selectYears: "Select years",
    lessThan1Year: "Less than 1 year",
    years: "years",
    previousCurrentCompany: "Previous/Current company",
    selectSkillsDesc: "Select all skills that apply to you",
    additionalInformation: "Additional Information",
    portfolioLinkedinUrl: "Portfolio/LinkedIn URL",
    portfolioPlaceholder: "https://linkedin.com/in/yourprofile or portfolio link",
    resumeUpload: "Resume Upload",
    resumeUploadDesc: "Upload your resume (PDF, DOC, DOCX - Max 5MB)",
    completeRegistration: "Complete Registration",
    back: "Back to Home",
    // Skill names (ensure no duplicate keys)
    JavaScript: "JavaScript",
    Python: "Python",
    React: "React",
    "Node.js": "Node.js",
    Java: "Java",
    "C++": "C++",
    "HTML/CSS": "HTML/CSS",
    "Graphic Design": "Graphic Design",
    "Digital Marketing": "Digital Marketing",
    "Content Writing": "Content Writing",
    "Data Analysis": "Data Analysis",
    Excel: "Excel",
    Communication: "Communication",
    Leadership: "Leadership",
    "Project Management": "Project Management",
    Sales: "Sales",
    "Customer Service": "Customer Service",
    "Social Media": "Social Media",
    Photography: "Photography",
    "Video Editing": "Video Editing",
    // --- Owner Register Specific ---
    "Business Owner Registration": "Business Owner Registration",
    "Join JBS as a business owner and connect with talented students": "Join JBS as a business owner and connect with talented students",
    "Personal Information": "Personal Information",
    "Owner Name": "Owner Name",
    "Enter your full name": "Enter your full name",
    "Email": "Email",
    "Enter your email": "Enter your email",
    "Date of Birth": "Date of Birth",
    "Pick a date": "Pick a date",
    "Gender": "Gender",
    "Select gender": "Select gender",
    "Phone Number": "Phone Number",
    "Enter your phone number": "Enter your phone number",
    "Enter your city": "Enter your city",
    "Enter your complete address": "Enter your complete address",
    "Business Information": "Business Information",
    "Company Name": "Company Name",
    "Enter your company name": "Enter your company name",
    "Company Location": "Company Location",
    "Enter company location": "Enter company location",
    "Business Type": "Business Type",
    "Select business type": "Select business type",
    "Company Size": "Company Size",
    "Select company size": "Select company size",
    "1-10 employees": "1-10 employees",
    "11-50 employees": "11-50 employees",
    "51-200 employees": "51-200 employees",
    "200+ employees": "200+ employees",
    "Founded Year": "Founded Year",
    "Enter founding year": "Enter founding year",
    "Website URL": "Website URL",
    "https://yourcompany.com": "https://yourcompany.com",
    "Business Description": "Business Description",
    "Describe your business, what you do, and what you're looking for in students...": "Describe your business, what you do, and what you're looking for in students...",
    "Product Categories": "Product Categories",
    "Select all categories that apply to your business": "Select all categories that apply to your business",
    "Legal Information (Optional)": "Legal Information (Optional)",
    "GST Number": "GST Number",
    "Enter GST number": "Enter GST number",
    "PAN Number": "PAN Number",
    "Enter PAN number": "Enter PAN number",
    "Business License/Registration Certificate": "Business License/Registration Certificate",
    "Upload business license or registration certificate (PDF, JPG, PNG - Max 10MB)": "Upload business license or registration certificate (PDF, JPG, PNG - Max 10MB)",
    "Complete Registration": "Complete Registration",
    "Missing Information": "Missing Information",
    "Please fill in all required fields.": "Please fill in all required fields.",
    "Product Categories Required": "Product Categories Required",
    "Please select at least one product category.": "Please select at least one product category.",
    "Registration Successful!": "Registration Successful!",
    "Welcome to JBS Platform. Redirecting to your dashboard...": "Welcome to JBS Platform. Redirecting to your dashboard...",
    "Registration Failed": "Registration Failed",
    "Please try again later.": "Please try again later.",
    // --- Business Types (Owner Register) ---
    "Retail Store": "Retail Store",
    "Restaurant/Food Service": "Restaurant/Food Service",
    "Electronics Store": "Electronics Store",
    "Clothing Store": "Clothing Store",
    "Grocery Store": "Grocery Store",
    "Pharmacy": "Pharmacy",
    "Bookstore": "Bookstore",
    "Hardware Store": "Hardware Store",
    "Beauty Salon": "Beauty Salon",
    "Fitness Center": "Fitness Center",
    "Educational Institute": "Educational Institute",
    "Healthcare Service": "Healthcare Service",
    "IT Services": "IT Services",
    "Manufacturing": "Manufacturing",
    "Trading": "Trading",
    "E-commerce": "E-commerce",
    "Consultancy": "Consultancy",
    "Other": "Other",
    // --- Product Categories (Owner Register) ---
    "Electronics": "Electronics",
    "Clothing & Fashion": "Clothing & Fashion",
    "Food & Beverages": "Food & Beverages",
    "Books & Stationery": "Books & Stationery",
    "Home & Garden": "Home & Garden",
    "Sports & Fitness": "Sports & Fitness",
    "Beauty & Personal Care": "Beauty & Personal Care",
    "Automotive": "Automotive",
    "Toys & Games": "Toys & Games",
    "Health & Medicine": "Health & Medicine",
    "Jewelry & Accessories": "Jewelry & Accessories",
    "Art & Crafts": "Art & Crafts",
    "Music & Instruments": "Music & Instruments",
    "Pet Supplies": "Pet Supplies",
    "Office Supplies": "Office Supplies",
    "Tools & Hardware": "Tools & Hardware"
  },
  
  hi: {
    // Navigation
    home: "होम",
    about: "के बारे में",
    jobs: "नौकरियां",
    internships: "इंटर्नशिप",
    buyProducts: "उत्पाद खरीदें",
    sellItems: "वस्तु बेचें",
    contact: "संपर्क",
    login: "लॉगिन",
    signup: "साइन अप",
    
    // Hero Section - New translations
    connectingSkills: "कौशल और वाणिज्य को जोड़ना",
    underOneRoof: "एक छत के नीचे",
    heroDescriptionNew: "चाहे आप अवसर तलाश रहे हों या प्रदान कर रहे हों, JBS छात्रों, पेशेवरों और व्यापार मालिकों के फलते-फूलते समुदाय का आपका प्रवेश द्वार है।",
    exploreJobsInternships: "नौकरियां और इंटर्नशिप देखें",
    startSellingHiring: "बेचना या भर्ती शुरू करें",
    
    // Stats - New translations
    activeUsers: "सक्रिय उपयोगकर्ता",
    jobsPosted: "पोस्ट की गई नौकरियां",
    itemsSold: "बेची गई वस्तुएं",
    internshipsOffered: "प्रस्तावित इंटर्नशिप",
    
    // Categories - New translations
    exploreByCategory: "श्रेणी के अनुसार देखें",
    findOpportunities: "पार्ट-टाइम और फुल-टाइम अवसर खोजें",
    gainExperience: "शीर्ष कंपनियों के साथ अनुभव प्राप्त करें",
    shopFromLocal: "स्थानीय विक्रेताओं से खरीदारी करें",
    listProducts: "अपने उत्पादों को आसानी से सूचीबद्ध करें",
    
    // Sections - New translations
    latestJobs: "नवीनतम नौकरियां",
    latestInternships: "नवीनतम इंटर्नशिप",
    trendingProducts: "ट्रेंडिंग उत्पाद",
    
    // Product specific
    outOfStock: "स्टॉक में नहीं",
    soldBy: "द्वारा बेचा गया:",
    
    // About section
    aboutPlatformTitle: "JBS प्लेटफॉर्म के बारे में",
    aboutPlatformDesc: "JBS (नौकरियां, खरीदारी और बिक्री) एक क्रांतिकारी प्लेटफॉर्म है जो अवसर तलाशने वाले छात्रों और प्रतिभा की तलाश करने वाले व्यवसायों के बीच अंतर को पाटता है।",
    forStudents: "छात्रों के लिए",
    forStudentsDesc: "अपना करियर बनाते समय अंशकालिक नौकरियां, इंटर्नशिप खोजें और आवश्यक चीजों की खरीदारी करें।",
    forBusinesses: "व्यवसायों के लिए", 
    forBusinessesDesc: "प्रतिभाशाली छात्रों को काम पर रखें, उत्पाद बेचें और हमारे प्लेटफॉर्म के साथ अपना व्यवसाय बढ़ाएं।",
    forGrowth: "विकास के लिए",
    forGrowthDesc: "सभी उपयोगकर्ताओं के लिए विकास, सीखने और पारस्परिक सफलता को बढ़ावा देने के लिए डिज़ाइन किया गया प्लेटफॉर्म।",
    
    // Testimonials
    whatUsersSay: "हमारे उपयोगकर्ता क्या कहते हैं",
    
    // Newsletter  
    stayUpdated: "अपडेट रहें",
    newsletterDescNew: "नवीनतम नौकरी पोस्टिंग, उत्पाद और प्लेटफॉर्म अपडेट प्राप्त करने के लिए सब्सक्राइब करें।",
    enterEmail: "अपना ईमेल दर्ज करें",
    
    // Footer
    footerDesc: "एक छत के नीचे कौशल और वाणिज्य को जोड़ना।",
    contactInfo: "संपर्क जानकारी",
    
    // Login/Signup forms
    loginToJBS: "JBS में लॉगिन करें",
    email: "ईमेल",
    password: "पासवर्ड",
    selectUserType: "उपयोगकर्ता प्रकार चुनें",
    studentJobSeeker: "छात्र/नौकरी तलाशने वाला", 
    shopOwnerBusiness: "दुकान मालिक/व्यवसाय",
    dontHaveAccount: "कोई खाता नहीं है?",
    joinJBSPlatform: "JBS प्लेटफॉर्म में शामिल हों",
    fullName: "पूरा नाम",
    continueRegistration: "पंजीकरण जारी रखें",
    alreadyHaveAccount: "पहले से खाता है?",
    
    // Cart
    shoppingCart: "शॉपिंग कार्ट",
    remove: "हटाएं",
    proceedToCheckout: "चेकआउट के लिए आगे बढ़ें",
    
    // Chatbot
    jbsAssistant: "JBS सहायक",
    askAnything: "JBS के बारे में मुझसे कुछ भी पूछें...",
    send: "भेजें",
    chatbotWelcome: "नमस्ते! मैं आपका JBS सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?",
    chatbotResponse: "उपयोगकर्ता के प्रश्न के लिए धन्यवाद! हमारी टीम जल्द ही आपसे संपर्क करेगी।",
    
    // Common
    items: "वस्तुएं",
    cartEmpty: "आपका कार्ट खाली है",
    
    // Form placeholders
    selectUserTypePlaceholder: "उपयोगकर्ता प्रकार चुनें",
    iAmA: "मैं हूं...",
    
    // Features
    features: "सुविधाएं",
    company: "कंपनी",
    description: "विवरण",
    requirements: "आवश्यकताएं",
    skills: "कौशल",
    
    // Sections
    aboutTitle: "JBS प्लेटफॉर्म के बारे में",
    aboutDescription: "JBS एक क्रांतिकारी प्लेटफॉर्म है।",
    whyChooseUs: "हमें क्यों चुनें",
    trustedPlatform: "विश्वसनीय प्लेटफॉर्म",
    trustedDesc: "सत्यापित व्यवसाय और सुरक्षित लेनदेन",
    flexibleOpportunities: "लचीले अवसर",
    flexibleDesc: "आपके समय के अनुकूल अंशकालिक नौकरियां",
    studentFocused: "छात्र-केंद्रित",
    studentDesc: "विशेष रूप से छात्रों की जरूरतों के लिए डिज़ाइन किया गया",
    localConnect: "स्थानीय कनेक्शन",
    localDesc: "अपने क्षेत्र के व्यवसायों से जुड़ें",
    
    // Featured sections
    featuredJobs: "विशेष नौकरियां",
    viewAllJobs: "सभी नौकरियां देखें",
    featuredInternships: "विशेष इंटर्नशिप",
    viewAllInternships: "सभी इंटर्नशिप देखें",
    viewAllProducts: "सभी उत्पाद देखें",
    
    // Buttons and actions
    applyNow: "अभी आवेदन करें",
    addToCart: "कार्ट में डालें",
    buyNow: "अभी खरीदें",
    learnMore: "और जानें",
    viewDetails: "विवरण देखें",
    
    // Product form
    addNewProduct: "नया उत्पाद जोड़ें",
    basicInformation: "बुनियादी जानकारी",
    productName: "उत्पाद का नाम",
    enterProductName: "उत्पाद का नाम दर्ज करें",
    brand: "ब्रांड",
    enterBrand: "ब्रांड का नाम दर्ज करें",
    originalPrice: "मूल कीमत",
    quantity: "मात्रा",
    selectCategory: "श्रेणी चुनें",
    condition: "स्थिति",
    new: "नया",
    likeNew: "नए जैसा",
    good: "अच्छा",
    fair: "ठीक",
    used: "उपयोग किया गया",
    productDetails: "उत्पाद विवरण",
    enterProductDescription: "विस्तृत उत्पाद विवरण दर्ज करें",
    keyFeatures: "मुख्य विशेषताएं",
    enterKeyFeatures: "मुख्य विशेषताएं दर्ज करें (प्रति पंक्ति एक)",
    productImages: "उत्पाद की छवियां",
    clickToUploadImages: "छवियां अपलोड करने के लिए क्लिक करें या खींचकर छोड़ें",
    supportedFormats: "PNG, JPG, GIF 10MB तक",
    availability: "उपलब्धता",
    productAdded: "उत्पाद जोड़ा गया",
    productAddedSuccessfully: "आपका उत्पाद सफलतापूर्वक जोड़ा गया!",
    addProduct: "उत्पाद जोड़ें",
    
    // Form labels and buttons
    fullTime: "पूर्णकालिक",
    partTime: "अंशकालिक",
    paid: "वेतनभोगी",
    unpaid: "बिना वेतन",
    inStock: "स्टॉक में",
    all: "सभी",
    
    // Toast messages
    addedToCart: "कार्ट में जोड़ा गया",
    removedFromCart: "कार्ट से हटाया गया",
    subscribedSuccessfully: "सफलतापूर्वक सब्सक्राइब किया गया!",
    thankYouForQuestion: "आपके प्रश्न के लिए धन्यवाद! हमारी टीम जल्द ही आपसे संपर्क करेगी। तत्काल सहायता के लिए, आप हमारे सहायता केंद्र को +91-9876543210 पर भी कॉल कर सकते हैं।",
    itemAddedToCart: "आपके कार्ट में जोड़ा गया है।",
    itemRemovedFromCart: "आइटम आपके कार्ट से हटा दिया गया है।",
    receiveLatestUpdates: "आपको अपने ईमेल में नवीनतम अपडेट प्राप्त होंगे।",
    
    // Footer and other UI elements
    quickLinks: "त्वरित लिंक",
    followUs: "हमें फॉलो करें",
    allRightsReserved: "सर्वाधिकार सुरक्षित",
    
    // Admin specific translations
    admin: "एडमिन",
    adminLogin: "एडमिन लॉगिन",
    adminDashboard: "एडमिन डैशबोर्ड",
    accessAdminDashboard: "एडमिन डैशबोर्ड तक पहुंचें",
    loginToAdminDashboard: "एडमिन डैशबोर्ड में लॉगिन करें",
    adminCredentials: "एडमिन क्रेडेंशियल्स:",
    welcomeToJBSAdmin: "JBS एडमिन डैशबोर्ड में आपका स्वागत है",
    welcomeBack: "वापसी पर स्वागत है",
    loginSuccessful: "लॉगिन सफल",
    loginFailed: "लॉगिन विफल",
    invalidEmailPassword: "अमान्य ईमेल या पासवर्ड",
    loggedOut: "लॉगआउट",
    loggedOutSuccessfully: "आप सफलतापूर्वक लॉगआउट हो गए हैं",
    backToHome: "होम पर वापस जाएं",
    loggingIn: "लॉगिन हो रहा है...",
    enterAdminEmail: "एडमिन ईमेल दर्ज करें",
    enterPassword: "पासवर्ड दर्ज करें",
    
    // Admin Dashboard stats
    totalProducts: "कुल उत्पाद",
    totalSold: "कुल बिक्री",
    paidProducts: "भुगतान किए गए उत्पाद",
    unpaidProducts: "बिना भुगतान के उत्पाद",
    totalJobInternshipJoins: "कुल नौकरी/इंटर्नशिप जॉइन",
    paidJoins: "भुगतान किए गए जॉइन",
    unpaidJoins: "बिना भुगतान के जॉइन",
    
    // Admin Dashboard tables
    jobInternshipDetails: "नौकरी/इंटर्नशिप विवरण",
    jobInternship: "नौकरी/इंटर्नशिप",
    totalJoined: "कुल जुड़े",
    
    // Admin Products
    manageProducts: "उत्पाद प्रबंधित करें",
    qty: "मात्रा",
    sold: "बिका",
    payment: "भुगतान",
    seller: "विक्रेता",
    
    // Admin Jobs
    manageJobs: "नौकरियां प्रबंधित करें",
    addJob: "नौकरी जोड़ें",
    
    // Admin Internships
    manageInternships: "इंटर्नशिप प्रबंधित करें",
    addInternship: "इंटर्नशिप जोड़ें",
    
    // Admin Payments
    paymentDetails: "भुगतान विवरण",
    totalProductPayments: "कुल उत्पाद भुगतान",
    totalJobPayments: "कुल नौकरी भुगतान",
    totalInternshipPayments: "कुल इंटर्नशिप भुगतान",
    
    // Admin Owners
    businessOwners: "व्यवसाय मालिक",
    viewProfile: "प्रोफ़ाइल देखें",
    block: "ब्लॉक करें",
    
    // Dashboard
    dashboard: "डैशबोर्ड",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    myOrders: "मेरे ऑर्डर",
    analytics: "एनालिटिक्स",
    aiAssistant: "AI सहायक",
    products: "उत्पाद",
    postNewJob: "नई नौकरी पोस्ट करें",
    postNewInternship: "नई इंटर्नशिप पोस्ट करें",
    track: "ट्रैक करें",
    studentRegistration: "छात्र पंजीकरण",
    studentRegistrationDesc: "JBS में छात्र के रूप में शामिल हों और अद्भुत अवसर खोजें",
    personalInformation: "व्यक्तिगत जानकारी",
    enterFullName: "अपना पूरा नाम दर्ज करें",
    pickDate: "तारीख चुनें",
    selectGender: "लिंग चुनें",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    preferNotToSay: "कहना नहीं चाहूंगा",
    phoneNumber: "फोन नंबर",
    enterPhoneNumber: "अपना फोन नंबर दर्ज करें",
    city: "शहर",
    enterCity: "अपना शहर दर्ज करें",
    address: "पता",
    enterAddress: "अपना पूरा पता दर्ज करें",
    educationInformation: "शिक्षा संबंधी जानकारी",
    educationLevel: "शिक्षा स्तर",
    selectEducationLevel: "शिक्षा स्तर चुनें",
    "12thPass": "12वीं पास",
    undergraduate: "स्नातक (पढ़ाई जारी)",
    graduate: "स्नातक",
    postGraduate: "स्नातकोत्तर",
    diploma: "डिप्लोमा",
    certificateCourse: "प्रमाणपत्र पाठ्यक्रम",
    bioAboutYourself: "बायो / अपने बारे में",
    bioPlaceholder: "अपने बारे में, अपने लक्ष्यों के बारे में और आप क्या खोज रहे हैं, बताएं...",
    experience: "अनुभव",
    iHaveWorkExperience: "मेरे पास कार्य अनुभव है",
    yearsOfExperience: "अनुभव के वर्ष",
    selectYears: "वर्ष चुनें",
    lessThan1Year: "1 वर्ष से कम",
    years: "वर्ष",
    previousCurrentCompany: "पिछली/वर्तमान कंपनी",
    skills: "कौशल",
    selectSkillsDesc: "सभी लागू कौशल चुनें",
    additionalInformation: "अतिरिक्त जानकारी",
    portfolioLinkedinUrl: "पोर्टफोलियो/LinkedIn URL",
    portfolioPlaceholder: "https://linkedin.com/in/yourprofile या पोर्टफोलियो लिंक",
    resumeUpload: "रिज़्यूमे अपलोड करें",
    resumeUploadDesc: "अपना रिज़्यूमे अपलोड करें (PDF, DOC, DOCX - अधिकतम 5MB)",
    completeRegistration: "पंजीकरण पूरा करें",
    back: "होम पर वापस जाएं",
    // Skill names (ensure no duplicate keys)
    JavaScript: "जावास्क्रिप्ट",
    Python: "पाइथन",
    React: "रिएक्ट",
    "Node.js": "नोड.जेएस",
    Java: "जावा",
    "C++": "सी++",
    "HTML/CSS": "एचटीएमएल/सीएसएस",
    "Graphic Design": "ग्राफिक डिजाइन",
    "Digital Marketing": "डिजिटल मार्केटिंग",
    "Content Writing": "सामग्री लेखन",
    "Data Analysis": "डेटा विश्लेषण",
    Excel: "एक्सेल",
    Communication: "संचार",
    Leadership: "नेतृत्व",
    "Project Management": "परियोजना प्रबंधन",
    Sales: "सेल्स",
    "Customer Service": "ग्राहक सेवा",
    "Social Media": "सोशल मीडिया",
    Photography: "फोटोग्राफी",
    "Video Editing": "वीडियो எடிட்டிங்",
    // --- Owner Register Specific ---
    "Business Owner Registration": "व्यवसाय स्वामी पंजीकरण",
    "Join JBS as a business owner and connect with talented students": "JBS में व्यवसाय स्वामी के रूप में शामिल हों और प्रतिभाशाली छात्रों से जुड़ें",
    "Personal Information": "व्यक्तिगत जानकारी",
    "Owner Name": "स्वामी का नाम",
    "Enter your full name": "अपना पूरा नाम दर्ज करें",
    "Email": "ईमेल",
    "Enter your email": "अपना ईमेल दर्ज करें",
    "Date of Birth": "जन्म तिथि",
    "Pick a date": "तिथि चुनें",
    "Gender": "Gender",
    "Select gender": "Select gender",
    "Male": "Male",
    "Female": "Female",
    "Other": "Other",
    "Prefer not to say": "Prefer not to say",
    "Phone Number": "Phone Number",
    "Enter your phone number": "Enter your phone number",
    "City": "City",
    "Enter your city": "Enter your city",
    "Address": "Address",
    "Enter your complete address": "Enter your complete address",
    "Business Information": "Business Information",
    "Company Name": "Company Name",
    "Enter your company name": "Enter your company name",
    "Company Location": "Company Location",
    "Enter company location": "Enter company location",
    "Business Type": "Business Type",
    "Select business type": "Select business type",
    "Company Size": "Company Size",
    "Select company size": "Select company size",
    "1-10 employees": "1-10 employees",
    "11-50 employees": "11-50 employees",
    "51-200 employees": "51-200 employees",
    "200+ employees": "200+ employees",
    "Founded Year": "Founded Year",
    "Enter founding year": "Enter founding year",
    "Website URL": "Website URL",
    "https://yourcompany.com": "https://yourcompany.com",
    "Business Description": "Business Description",
    "Describe your business, what you do, and what you're looking for in students...": "Describe your business, what you do, and what you're looking for in students...",
    "Product Categories": "Product Categories",
    "Select all categories that apply to your business": "Select all categories that apply to your business",
    "Legal Information (Optional)": "Legal Information (Optional)",
    "GST Number": "GST Number",
    "Enter GST number": "Enter GST number",
    "PAN Number": "PAN Number",
    "Enter PAN number": "Enter PAN number",
    "Business License/Registration Certificate": "Business License/Registration Certificate",
    "Upload business license or registration certificate (PDF, JPG, PNG - Max 10MB)": "Upload business license or registration certificate (PDF, JPG, PNG - Max 10MB)",
    "Complete Registration": "Complete Registration",
    "Missing Information": "Missing Information",
    "Please fill in all required fields.": "Please fill in all required fields.",
    "Product Categories Required": "Product Categories Required",
    "Please select at least one product category.": "Please select at least one product category.",
    "Registration Successful!": "Registration Successful!",
    "Welcome to JBS Platform. Redirecting to your dashboard...": "Welcome to JBS Platform. Redirecting to your dashboard...",
    "Registration Failed": "Registration Failed",
    "Please try again later.": "Please try again later.",
    // --- Business Types (Owner Register) ---
    "Retail Store": "Retail Store",
    "Restaurant/Food Service": "Restaurant/Food Service",
    "Electronics Store": "Electronics Store",
    "Clothing Store": "Clothing Store",
    "Grocery Store": "Grocery Store",
    "Pharmacy": "Pharmacy",
    "Bookstore": "Bookstore",
    "Hardware Store": "Hardware Store",
    "Beauty Salon": "Beauty Salon",
    "Fitness Center": "Fitness Center",
    "Educational Institute": "Educational Institute",
    "Healthcare Service": "Healthcare Service",
    "IT Services": "IT Services",
    "Manufacturing": "Manufacturing",
    "Trading": "Trading",
    "E-commerce": "E-commerce",
    "Consultancy": "Consultancy",
    "Other": "Other",
    // --- Product Categories (Owner Register) ---
    "Electronics": "Electronics",
    "Clothing & Fashion": "Clothing & Fashion",
    "Food & Beverages": "Food & Beverages",
    "Books & Stationery": "Books & Stationery",
    "Home & Garden": "Home & Garden",
    "Sports & Fitness": "Sports & Fitness",
    "Beauty & Personal Care": "Beauty & Personal Care",
    "Automotive": "Automotive",
    "Toys & Games": "Toys & Games",
    "Health & Medicine": "Health & Medicine",
    "Jewelry & Accessories": "Jewelry & Accessories",
    "Art & Crafts": "Art & Crafts",
    "Music & Instruments": "Music & Instruments",
    "Pet Supplies": "Pet Supplies",
    "Office Supplies": "Office Supplies",
    "Tools & Hardware": "Tools & Hardware"
  },
  
  ta: {
    // Navigation
    home: "முகப்பு",
    about: "பற்றி",
    jobs: "வேலைகள்",
    internships: "பயிற்சி",
    buyProducts: "தயாரிப்புகள் வாங்க",
    sellItems: "பொருட்கள் விற்க",
    contact: "தொடர்பு",
    login: "உள்நுழை",
    signup: "பதிவு செய்க",
    
    // Hero Section - New translations
    connectingSkills: "திறமை மற்றும் வணிகத்தை இணைக்கிறது",
    underOneRoof: "ஒரே கூரையின் கீழ்",
    heroDescriptionNew: "நீங்கள் வாய்ப்புகளைத் தேடுகிறீர்களா அல்லது வழங்குகிறீர்களா, மாணவர்கள், தொழில் வல்லுநர்கள் மற்றும் வணிக உரிமையாளர்களின் செழிப்பான சமூகத்திற்கான உங்கள் நுழைவாயில் JBS ஆகும்.",
    exploreJobsInternships: "வேலைகள் மற்றும் பயிற்சிகளை ஆராயுங்கள்",
    startSellingHiring: "விற்பனை அல்லது பணியமர்த்தலைத் தொடங்குங்கள்",
    
    // Stats - New translations
    activeUsers: "செயலில் உள்ள பயனர்கள்",
    jobsPosted: "இடுகையிடப்பட்ட வேலைகள்",
    itemsSold: "விற்கப்பட்ட பொருட்கள்",
    internshipsOffered: "வழங்கப்பட்ட பயிற்சிகள்",
    
    // Categories - New translations
    exploreByCategory: "வகை வாரியாக ஆராயுங்கள்",
    findOpportunities: "பகுதி நேர மற்றும் முழு நேர வாய்ப்புகளைக் கண்டறியுங்கள்",
    gainExperience: "முன்னணி நிறுவனங்களுடன் அனுபவம் பெறுங்கள்",
    shopFromLocal: "உள்ளூர் விற்பனையாளர்களிடமிருந்து வாங்குங்கள்",
    listProducts: "உங்கள் தயாரிப்புகளை எளிதாக பட்டியலிடுங்கள்",
    
    // Sections - New translations
    latestJobs: "சமீபத்திய வேலைகள்",
    latestInternships: "சமீபத்திய பயிற்சிகள்",
    trendingProducts: "பிரபலமான தயாரிப்புகள்",
    
    // Product specific
    outOfStock: "கையிருப்பில் இல்லை",
    soldBy: "விற்பனையாளர்:",
    
    // About section
    aboutPlatformTitle: "JBS தளம் பற்றி",
    aboutPlatformDesc: "JBS என்பது ஒரு புரட்சிகர தளமாகும்.",
    forStudents: "மாணவர்களுக்கு",
    forStudentsDesc: "உங்கள் தொழில் வாழ்க்கையை உருவாக்கும் போது பகுதி நேர வேலைகள், பயிற்சிகளைக் கண்டறிந்து அத்தியாவசிய பொருட்களை வாங்குங்கள்.",
    forBusinesses: "வணிகங்களுக்கு",
    forBusinessesDesc: "திறமையான மாணவர்களை வேலைக்கு அமர்த்துங்கள், தயாரிப்புகளை விற்பனை செய்யுங்கள்.",
    forGrowth: "வளர்ச்சிக்காக",
    forGrowthDesc: "அனைத்து பயனர்களுக்கும் வளர்ச்சியை வளர்க்க வடிவமைக்கப்பட்ட ஒரு தளம்.",
    
    // Testimonials
    whatUsersSay: "எங்கள் பயனர்கள் என்ன சொல்கிறார்கள்",
    
    // Newsletter
    stayUpdated: "புதுப்பித்த நிலையில் இருங்கள்",
    newsletterDescNew: "சமீபத்திய வேலை இடுகைகள், தயாரிப்புகள் மற்றும் தளம் புதுப்பிப்புகளைப் பெற சந்தா செலுத்துங்கள்.",
    enterEmail: "உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்",
    
    // Footer
    footerDesc: "ஒரே கூரையின் கீழ் திறமை மற்றும் வணிகத்தை இணைக்கிறது.",
    contactInfo: "தொடர்பு தகவல்",
    
    // Login/Signup forms
    loginToJBS: "JBS இல் உள்நுழைக",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    selectUserType: "பயனர் வகையைத் தேர்ந்தெடுக்கவும்",
    studentJobSeeker: "மாணவர்/வேலை தேடுபவர்",
    shopOwnerBusiness: "கடை உரிமையாளர்/வணிகம்",
    dontHaveAccount: "கணக்கு இல்லையா?",
    joinJBSPlatform: "JBS தளத்தில் சேரவும்",
    fullName: "முழு பெயர்",
    continueRegistration: "பதிவை தொடரவும்",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    
    // Cart
    shoppingCart: "வாங்குதல் கார்ட்",
    remove: "அகற்று",
    proceedToCheckout: "பணம் செலுத்த செல்லவும்",
    
    // Chatbot
    jbsAssistant: "JBS உதவியாளர்",
    askAnything: "JBS பற்றி எதுவும் என்னிடம் கேளுங்கள்...",
    send: "அனுப்பு",
    chatbotWelcome: "வணக்கம்! நான் உங்கள் JBS உதவியாளர்.",
    chatbotResponse: "உங்கள் கேள்விக்கு நன்றி! எங்கள் குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும்.",
    
    // Common
    items: "பொருட்கள்",
    cartEmpty: "உங்கள் கார்ட் காலியாக உள்ளது",
    
    // Form placeholders
    selectUserTypePlaceholder: "பயனர் வகையைத் தேர்ந்தெடுக்கவும்",
    iAmA: "நான்...",
    
    // Features
    features: "அம்சங்கள்",
    company: "நிறுவனம்",
    description: "விவரம்",
    requirements: "தேவைகள்",
    skills: "திறன்கள்",
    
    // Sections
    aboutTitle: "JBS தளம் பற்றி",
    aboutDescription: "JBS ஒரு புரட்சிகர தளமாகும்.",
    whyChooseUs: "எங்களை ஏன் தேர்வு செய்ய வேண்டும்",
    trustedPlatform: "நம்பகமான தளம்",
    trustedDesc: "சரிபார்க்கப்பட்ட வணிகங்கள் மற்றும் பாதுகாப்பான பரிவர்த்தனைகள்",
    flexibleOpportunities: "நெகிழ்வான வாய்ப்புகள்",
    flexibleDesc: "உங்கள் அட்டவணைக்கு ஏற்ற பகுதி நேர வேலைகள்",
    studentFocused: "மாணவர்-மையம்",
    studentDesc: "மாணவர் தேவைகளுக்காக குறிப்பாக வடிவமைக்கப்பட்டது",
    localConnect: "உள்ளூர் இணைப்பு",
    localDesc: "உங்கள் பகுதியில் உள்ள வணிகங்களுடன் இணையுங்கள்",
    
    // Featured sections
    featuredJobs: "சிறப்பு வேலைகள்",
    viewAllJobs: "அனைத்து வேலைகளையும் பார்க்கவும்",
    featuredInternships: "சிறப்பு பயிற்சி",
    viewAllInternships: "அனைத்து பயிற்சிகளையும் பார்க்கவும்",
    viewAllProducts: "அனைத்து தயாரிப்புகளையும் பார்க்கவும்",
    
    // Buttons and actions
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    addToCart: "கார்ட்டில் சேர்க்கவும்",
    buyNow: "இப்போது வாங்கவும்",
    learnMore: "மேலும் அறிக",
    viewDetails: "விவரங்களைப் பார்க்கவும்",
    
    // Product form
    addNewProduct: "புதிய தயாரிப்பு சேர்க்கவும்",
    basicInformation: "அடிப்படை தகவல்",
    productName: "தயாரிப்பு பெயர்",
    enterProductName: "தயாரிப்பு பெயரை உள்ளிடவும்",
    brand: "பிராண்ட்",
    enterBrand: "பிராண்ட் பெயரை உள்ளிடவும்",
    originalPrice: "அசல் விலை",
    quantity: "அளவு",
    selectCategory: "வகையைத் தேர்ந்தெடுக்கவும்",
    condition: "நிலை",
    new: "புதிய",
    likeNew: "புதியது போல",
    good: "நல்லது",
    fair: "சரியானது",
    used: "பயன்படுத்தப்பட்டது",
    productDetails: "தயாரிப்பு விவரங்கள்",
    enterProductDescription: "விரிவான தயாரிப்பு விவரணத்தை உள்ளிடவும்",
    keyFeatures: "முக்கிய அம்சங்கள்",
    enterKeyFeatures: "முக்கிய அம்சங்களை உள்ளிடவும் (ஒரு வரிக்கு ஒன்று)",
    productImages: "தயாரிப்பு படங்கள்",
    clickToUploadImages: "படங்களை பதிவேற்ற கிளிக் செய்யவும் அல்லது இழுத்து விடவும்",
    supportedFormats: "PNG, JPG, GIF 10MB வரை",
    availability: "கிடைக்கும் தன்மை",
    productAdded: "தயாரிப்பு சேர்க்கப்பட்டது",
    productAddedSuccessfully: "உங்கள் தயாரிப்பு வெற்றிகரமாக சேர்க்கப்பட்டது!",
    addProduct: "தயாரிப்பு சேர்க்கவும்",
    
    // Form labels and buttons
    fullTime: "முழு நேரம்",
    partTime: "பகுதி நேரம்",
    paid: "ஊதியம்",
    unpaid: "ஊதியம் இல்லாமல்",
    inStock: "கையிருப்பில்",
    all: "அனைத்து",
    
    // Toast messages
    addedToCart: "கார்ட்டில் சேர்க்கப்பட்டது",
    removedFromCart: "கார்ட்டிலிருந்து அகற்றப்பட்டது",
    subscribedSuccessfully: "வெற்றிகரமாக சந்தா செலுத்தப்பட்டது!",
    thankYouForQuestion: "உங்கள் கேள்விக்கு நன்றி! எங்கள் குழு விரைவில் உங்களைத் தொடர்பு கொள்ளும். உடனடி உதவிக்கு, நீங்கள் எங்கள் ஆதரவு மையத்தை +91-9876543210 இல் அழைக்கலாம்.",
    itemAddedToCart: "உங்கள் கார்ட்டில் சேர்க்கப்பட்டுள்ளது.",
    itemRemovedFromCart: "பொருள் உங்கள் கார்ட்டிலிருந்து அகற்றப்பட்டுள்ளது.",
    receiveLatestUpdates: "நீங்கள் உங்கள் மின்னஞ்சலில் சமீபத்திய புதுப்பிப்புகளைப் பெறுவீர்கள்.",
    
    // Footer and other UI elements
    quickLinks: "விரைவு இணைப்புகள்",
    followUs: "எங்களைப் பின்தொடரவும்",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை",
    
    // Admin specific translations
    admin: "நிர்வாகி",
    adminLogin: "நிர்வாகி உள்நுழைவு",
    adminDashboard: "நிர்வாகி டாஷ்போர்டு",
    accessAdminDashboard: "நிர்வாகி டாஷ்போர்டுக்கு அணுகல்",
    loginToAdminDashboard: "நிர்வாகி டாஷ்போர்டில் உள்நுழையவும்",
    adminCredentials: "நிர்வாகி அடையாளங்கள்:",
    welcomeToJBSAdmin: "JBS நிர்வாகி டாஷ்போர்டுக்கு வரவேற்கிறோம்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    loginSuccessful: "உள்நுழைவு வெற்றி",
    loginFailed: "உள்நுழைவு தோல்வி",
    invalidEmailPassword: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்",
    loggedOut: "வெளியேறியது",
    loggedOutSuccessfully: "நீங்கள் வெற்றிகரமாக வெளியேறியுள்ளீர்கள்",
    backToHome: "முகப்புக்கு திரும்பவும்",
    loggingIn: "உள்நுழைகிறது...",
    enterAdminEmail: "நிர்வாகி மின்னஞ்சலை உள்ளிடவும்",
    enterPassword: "கடவுச்சொல்லை உள்ளிடவும்",
    
    // Admin Dashboard stats
    totalProducts: "மொத்த தயாரிப்புகள்",
    totalSold: "மொத்த விற்பனை",
    paidProducts: "பணம் செலுத்தப்பட்ட தயாரிப்புகள்",
    unpaidProducts: "பணம் செலுத்தப்படாத தயாரிப்புகள்",
    totalJobInternshipJoins: "மொத்த வேலை/பயிற்சி சேர்ப்புகள்",
    paidJoins: "பணம் செலுத்தப்பட்ட சேர்ப்புகள்",
    unpaidJoins: "பணம் செலுத்தப்படாத சேர்ப்புகள்",
    
    // Admin Dashboard tables
    jobInternshipDetails: "வேலை/பயிற்சி விவரங்கள்",
    jobInternship: "வேலை/பயிற்சி",
    totalJoined: "மொத்த சேர்ந்தவர்கள்",
    
    // Admin Products
    manageProducts: "தயாரிப்புகளை நிர்வகிக்கவும்",
    addProduct: "தயாரிப்பு சேர்க்கவும்",
    qty: "அளவு",
    sold: "விற்கப்பட்டது",
    payment: "பணம் செலுத்துதல்",
    seller: "விற்பனையாளர்",
    
    // Admin Jobs
    manageJobs: "வேலைகளை நிர்வகிக்கவும்",
    addJob: "வேலை சேர்க்கவும்",
    
    // Admin Internships
    manageInternships: "பயிற்சிகளை நிர்வகிக்கவும்",
    addInternship: "பயிற்சி சேர்க்கவும்",
    
    // Admin Payments
    paymentDetails: "பணம் செலுத்தும் விவரங்கள்",
    totalProductPayments: "மொத்த தயாரிப்பு பணம் செலுத்துதல்",
    totalJobPayments: "மொத்த வேலை பணம் செலுத்துதல்",
    totalInternshipPayments: "மொத்த பயிற்சி பணம் செலுத்துதல்",
    
    // Admin Owners
    businessOwners: "வணிக உரிமையாளர்கள்",
    viewProfile: "சுயவிவரத்தைக் காண்க",
    block: "தடுக்கவும்",
    
    // Dashboard
    dashboard: "டாஷ்போர்டு",
    profile: "சுயவிவரம்",
    settings: "அமைப்புகள்",
    notifications: "அறிவிப்புகள்",
    myOrders: "எனது ஆர்டர்கள்",
    analytics: "பகுப்பாய்வு",
    aiAssistant: "AI உதவியாளர்",
    products: "தயாரிப்புகள்",
    postNewJob: "புதிய வேலை இடுகை",
    postNewInternship: "புதிய பயிற்சி இடுகை",
    track: "கண்காணிக்கவும்",
    studentRegistration: "மாணவர் பதிவு",
    studentRegistrationDesc: "JBS இல் மாணவராக சேர்ந்து சிறந்த வாய்ப்புகளை கண்டறியுங்கள்",
    personalInformation: "வ்யக்குதிப்பட்ட தகவல்",
    enterFullName: "உங்கள் முழு பெயரை உள்ளிடவும்",
    pickDate: "தேதியைத் தேர்ந்தெடுக்கவும்",
    selectGender: "பாலினம் தேர்ந்தெடுக்கவும்",
    male: "ஆண்",
    female: "பெண்",
    other: "மற்றவை",
    preferNotToSay: "கூற விரும்பவில்லை",
    phoneNumber: "தொலைபேசி எண்",
    enterPhoneNumber: "உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்",
    city: "நகரம்",
    enterCity: "உங்கள் நகரத்தை உள்ளிடவும்",
    address: "முகவரி",
    enterAddress: "உங்கள் முழு முகவரியை உள்ளிடவும்",
    educationInformation: "கல்வி தகவல்",
    educationLevel: "கல்வி நிலை",
    selectEducationLevel: "கல்வி நிலையைத் தேர்ந்தெடுக்கவும்",
    "12thPass": "12வது தேர்ச்சி",
    undergraduate: "பட்டப்படிப்பு (படிப்பு தொடர்கிறது)",
    graduate: "பட்டதாரி",
    postGraduate: "முதுகலை",
    diploma: "டிப்ளோமா",
    certificateCourse: "சான்றிதழ் பாடநெறி",
    bioAboutYourself: "உங்கள் குறிப்பு / உங்களைப் பற்றி",
    bioPlaceholder: "உங்களைப் பற்றி, உங்கள் இலக்குகள் மற்றும் நீங்கள் தேடும் விஷயங்களைச் சொல்லுங்கள்...",
    experience: "அனுபவம்",
    iHaveWorkExperience: "எனக்கு வேலை அனுபவம் உள்ளது",
    yearsOfExperience: "அனுபவ ஆண்டுகள்",
    selectYears: "ஆண்டுகளைத் தேர்ந்தெடுக்கவும்",
    lessThan1Year: "1 ஆண்டுக்கு குறைவாக",
    years: "ஆண்டுகள்",
    previousCurrentCompany: "முந்தைய/தற்போதைய நிறுவனம்",
    skills: "திறன்கள்",
    selectSkillsDesc: "உங்களுக்கு பொருந்தும் அனைத்து திறன்களையும் தேர்ந்தெடுக்கவும்",
    additionalInformation: "கூடுதல் தகவல்",
    portfolioLinkedinUrl: "போர்ட்ஃபோலியோ/LinkedIn URL",
    portfolioPlaceholder: "https://linkedin.com/in/yourprofile அல்லது போர்ட்ஃபோலியோ இணைப்பு",
    resumeUpload: "ரெஸ்யூம் பதிவேற்றம்",
    resumeUploadDesc: "உங்கள் ரெஸ்யூமை பதிவேற்றவும் (PDF, DOC, DOCX - அதிகபட்சம் 5MB)",
    completeRegistration: "பதிவை முடிக்கவும்",
    back: "முகப்புக்கு திரும்பவும்",
    // Skill names (ensure no duplicate keys)
    JavaScript: "ஜாவாஸ்கிரிப்ட்",
    Python: "பைதான்",
    React: "ரியாக்ட்",
    "Node.js": "நோட்.ஜிஎஸ்",
    Java: "ஜாவா",
    "C++": "சி++",
    "HTML/CSS": "ஏசுட்டிஎஸ்சிஎஸ்",
    "Graphic Design": "கிராஃபிக் வடிவமைப்பு",
    "Digital Marketing": "டிஜிட்டல் மார்க்கெட்டிங்",
    "Content Writing": "உள்ளடக்கம் எழுதுதல்",
    "Data Analysis": "தரவு பகுப்பாய்வு",
    Excel: "எக்செல்",
    Communication: "தொடர்பு",
    Leadership: "தலைமை",
    "Project Management": "திட்ட மேலாண்மை",
    Sales: "விற்பனை",
    "Customer Service": "வாடிக்கையாளர் சேவை",
    "Social Media": "சமூக ஊடகம்",
    Photography: "புகைப்படம்",
    "Video Editing": "வீடியோ எடிட்டிங்",
    // --- Business Types (Owner Register) ---
    "Retail Store": "சில்லறை கடை",
    "Restaurant/Food Service": "உணவகம்/உணவு சேவை",
    "Electronics Store": "மின்னணு சாதனக் கடை",
    "Clothing Store": "ஆடைகள் கடை",
    "Grocery Store": "மளிகை கடை",
    "Pharmacy": "மருந்தகம்",
    "Bookstore": "புத்தகக் கடை",
    "Hardware Store": "ஹார்ட்வேர் கடை",
    "Beauty Salon": "அழகு நிலையம்",
    "Fitness Center": "உடற்பயிற்சி மையம்",
    "Educational Institute": "கல்வி நிறுவனம்",
    "Healthcare Service": "சுகாதார சேவை",
    "IT Services": "IT சேவைகள்",
    "Manufacturing": "தயாரிப்பு",
    "Trading": "வர்த்தகம்",
    "E-commerce": "மின்னணு வணிகம்",
    "Consultancy": "ஆலோசனை",
    "Other": "மற்றவை",
    // --- Product Categories (Owner Register) ---
    "Electronics": "மின்னணு சாதனங்கள்",
    "Clothing & Fashion": "ஆடைகள் மற்றும் ஃபேஷன்",
    "Food & Beverages": "உணவு மற்றும் பானங்கள்",
    "Books & Stationery": "புத்தகங்கள் மற்றும் எழுத்துப்பொருட்கள்",
    "Home & Garden": "வீடு மற்றும் தோட்டம்",
    "Sports & Fitness": "விளையாட்டு மற்றும் உடற்பயிற்சி",
    "Beauty & Personal Care": "அழகு மற்றும் தனிப்பட்ட பராமரிப்பு",
    "Automotive": "வாகனங்கள்",
    "Toys & Games": "பொம்மைகள் மற்றும் விளையாட்டுகள்",
    "Health & Medicine": "சுகாதாரம் மற்றும் மருந்து",
    "Jewelry & Accessories": "நகைகள் மற்றும் அணிகலன்கள்",
    "Art & Crafts": "கலை மற்றும் கைவினை",
    "Music & Instruments": "இசை மற்றும் இசைக்கருவிகள்",
    "Pet Supplies": "விலங்கு உபகரணங்கள்",
    "Office Supplies": "அலுவலக உபகரணங்கள்",
    "Tools & Hardware": "கருவிகள் மற்றும் ஹார்ட்வேர்",
    // --- Business Types (Owner Register) ---
    "Retail Store": "Retail Store",
    "Restaurant/Food Service": "Restaurant/Food Service",
    "Electronics Store": "Electronics Store",
    "Clothing Store": "Clothing Store",
    "Grocery Store": "Grocery Store",
    "Pharmacy": "Pharmacy",
    "Bookstore": "Bookstore",
    "Hardware Store": "Hardware Store",
    "Beauty Salon": "Beauty Salon",
    "Fitness Center": "Fitness Center",
    "Educational Institute": "Educational Institute",
    "Healthcare Service": "Healthcare Service",
    "IT Services": "IT Services",
    "Manufacturing": "Manufacturing",
    "Trading": "Trading",
    "E-commerce": "E-commerce",
    "Consultancy": "Consultancy",
    "Other": "Other",
    // --- Product Categories (Owner Register) ---
    "Electronics": "Electronics",
    "Clothing & Fashion": "Clothing & Fashion",
    "Food & Beverages": "Food & Beverages",
    "Books & Stationery": "Books & Stationery",
    "Home & Garden": "Home & Garden",
    "Sports & Fitness": "Sports & Fitness",
    "Beauty & Personal Care": "Beauty & Personal Care",
    "Automotive": "Automotive",
    "Toys & Games": "Toys & Games",
    "Health & Medicine": "Health & Medicine",
    "Jewelry & Accessories": "Jewelry & Accessories",
    "Art & Crafts": "Art & Crafts",
    "Music & Instruments": "Music & Instruments",
    "Pet Supplies": "Pet Supplies",
    "Office Supplies": "Office Supplies",
    "Tools & Hardware": "Tools & Hardware",
    // --- Owner Register Specific ---
    "Business Owner Registration": "வணிக உரிமையாளர் பதிவு",
    "Join JBS as a business owner and connect with talented students": "JBS இல் வணிக உரிமையாளராக சேர்ந்து திறமையான மாணவர்களுடன் இணைக",
    "Personal Information": "தனிப்பட்ட தகவல்",
    "Owner Name": "உரிமையாளர் பெயர்",
    "Enter your full name": "உங்கள் முழு பெயரை உள்ளிடவும்",
    "Email": "மின்னஞ்சல்",
    "Enter your email": "உங்கள் மின்னஞ்சலை உள்ளிடுங்கள்",
    "Date of Birth": "பிறந்த தேதி",
    "Pick a date": "தேதியைத் தேர்ந்தெடுக்கவும்",
    "Gender": "Gender",
    "Select gender": "Select gender",
    "Male": "Male",
    "Female": "Female",
    "Other": "Other",
    "Prefer not to say": "Prefer not to say",
    "Phone Number": "Phone Number",
    "Enter your phone number": "Enter your phone number",
    "City": "City",
    "Enter your city": "Enter your city",
    "Address": "Address",
    "Enter your complete address": "Enter your complete address",
    "Business Information": "Business Information",
    "Company Name": "Company Name",
    "Enter your company name": "Enter your company name",
    "Company Location": "Company Location",
    "Enter company location": "Enter company location",
    "Business Type": "Business Type",
    "Select business type": "Select business type",
    "Company Size": "Company Size",
    "Select company size": "Select company size",
    "1-10 employees": "1-10 employees",
    "11-50 employees": "11-50 employees",
    "51-200 employees": "51-200 employees",
    "200+ employees": "200+ employees",
    "Founded Year": "Founded Year",
    "Enter founding year": "Enter founding year",
    "Website URL": "Website URL",
    "https://yourcompany.com": "https://yourcompany.com",
    "Business Description": "Business Description",
    "Describe your business, what you do, and what you're looking for in students...": "Describe your business, what you do, and what you're looking for in students...",
    "Product Categories": "Product Categories",
    "Select all categories that apply to your business": "Select all categories that apply to your business",
    "Legal Information (Optional)": "Legal Information (Optional)",
    "GST Number": "GST Number",
    "Enter GST number": "Enter GST number",
    "PAN Number": "PAN Number",
    "Enter PAN number": "Enter PAN number",
    "Business License/Registration Certificate": "Business License/Registration Certificate",
    "Upload business license or registration certificate (PDF, JPG, PNG - Max 10MB)": "Upload business license or registration certificate (PDF, JPG, PNG - Max 10MB)",
    "Complete Registration": "Complete Registration",
    "Missing Information": "Missing Information",
    "Please fill in all required fields.": "Please fill in all required fields.",
    "Product Categories Required": "Product Categories Required",
    "Please select at least one product category.": "Please select at least one product category.",
    "Registration Successful!": "Registration Successful!",
    "Welcome to JBS Platform. Redirecting to your dashboard...": "Welcome to JBS Platform. Redirecting to your dashboard...",
    "Registration Failed": "Registration Failed",
    "Please try again later.": "Please try again later.",
    // --- Business Types (Owner Register) ---
    "Retail Store": "Retail Store",
    "Restaurant/Food Service": "Restaurant/Food Service",
    "Electronics Store": "Electronics Store",
    "Clothing Store": "Clothing Store",
    "Grocery Store": "Grocery Store",
    "Pharmacy": "Pharmacy",
    "Bookstore": "Bookstore",
    "Hardware Store": "Hardware Store",
    "Beauty Salon": "Beauty Salon",
    "Fitness Center": "Fitness Center",
    "Educational Institute": "Educational Institute",
    "Healthcare Service": "Healthcare Service",
    "IT Services": "IT Services",
    "Manufacturing": "Manufacturing",
    "Trading": "Trading",
    "E-commerce": "E-commerce",
    "Consultancy": "Consultancy",
    "Other": "Other",
    // --- Product Categories (Owner Register) ---
    "Electronics": "Electronics",
    "Clothing & Fashion": "Clothing & Fashion",
    "Food & Beverages": "Food & Beverages",
    "Books & Stationery": "Books & Stationery",
    "Home & Garden": "Home & Garden",
    "Sports & Fitness": "Sports & Fitness",
    "Beauty & Personal Care": "Beauty & Personal Care",
    "Automotive": "Automotive",
    "Toys & Games": "Toys & Games",
    "Health & Medicine": "Health & Medicine",
    "Jewelry & Accessories": "Jewelry & Accessories",
    "Art & Crafts": "Art & Crafts",
    "Music & Instruments": "Music & Instruments",
    "Pet Supplies": "Pet Supplies",
    "Office Supplies": "Office Supplies",
    "Tools & Hardware": "Tools & Hardware"
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<string>(() => {
    // Force English language by default
    const savedLanguage = localStorage.getItem('jbs-language');
    if (savedLanguage && savedLanguage !== 'en') {
      // Clear any non-English language setting
      localStorage.removeItem('jbs-language');
    }
    return 'en';
  });

  const handleSetLanguage = (lang: string) => {
    setLanguage(lang);
    // Persist language selection to localStorage
    localStorage.setItem('jbs-language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};